### ISSUE TITLE
Feature: toggle via config/environment variable

### ISSUE THREAD

**Issue by jrnail23** [archfz/cypress-duration-metrics#3]
First of all, this is an excellent tool!
I'd love if it could be toggled on/off based on configuration or an environment variable.

**Comment by archfz** [comment]
Hi @jrnail23. I am seeing this request quite late.

However I don't think this needs to be implemented. You can enable it optionally with a cypress env config. Please see docs https://docs.cypress.io/guides/guides/environment-variables
